default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shipit_engine_development

test:
  <<: *default
  database: shipit_engine_test

production:
  <<: *default
  database: <%= ENV['SHIPIT_ENGINE_DATABASE_NAME'] %>
  username: <%= ENV['SHIPIT_ENGINE_DATABASE_USER'] %>
  password: <%= ENV['SHIPIT_ENGINE_DATABASE_PASSWORD'] %>
