version: '3.9'
services:
  postgresql:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    image: postgres
    ports:
      - 5432
    volumes:
      - .compose-data/postgresql:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-server:
    command: redis-server --appendonly yes
    image: redis:5-alpine
    ports:
      - 6379
    volumes:
      - .compose-data/redis:/data

  app:
    build: .
    depends_on:
      postgresql:
        condition: service_healthy
      redis-server:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:password@postgresql:5432
      - REDIS_URL=redis://redis-server:6379
      - SECRET_KEY_BASE=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    restart: on-failure
    volumes:
      - ${PWD}/config/secrets.yml:/usr/src/shipit/config/secrets.yml:ro
    ports:
      - 3000:3000

  worker:
    build: .
    depends_on:
      postgresql:
        condition: service_healthy
      redis-server:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:password@postgresql:5432
      - REDIS_URL=redis://redis-server:6379
      - SECRET_KEY_BASE=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    restart: on-failure
    volumes:
      - ${PWD}/config/secrets.yml:/usr/src/shipit/config/secrets.yml:ro
    command: bundle exec sidekiq -C config/sidekiq.yml
